apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jasca-pgdata
  namespace: jasca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jasca-redis
  namespace: jasca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jasca-scan-results
  namespace: jasca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jasca-trivy-db
  namespace: jasca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
